### PR TITLE
ok

### PR DESCRIPTION
**Pull request by Lacapsule66**

### CODE REVIEW

**Comment by Lacapsule66** [comment]
ok

**Comment by Lacapsule66** [comment]
ok

**Comment by Lacapsule66** [comment]
ok

**Comment by rpuls** [comment]
I recommend forking the repo, or launching it on Railway and ejecting, if you want to make changes.

Instructions here: https://youtu.be/PPxenu7IjGM?si=mubB_poEHcZ7aQEo 🙂

**Pull request closed without merging**
